apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: grafana-dev
  labels:
    app: grafana
data:
  grafana.ini: |
    [server]
    root_url = %(protocol)s://%(domain)s:%(http_port)s/
    [security]
    admin_user = ${GF_SECURITY_ADMIN_USER}
    admin_password = ${GF_SECURITY_ADMIN_PASSWORD}