apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: grafana-dev
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 32000
  selector:
    app: grafana
